main: logan.pickpocket.main.Pickpocket
name: PickPocket
version: v1.0.6
author: TTG_TRE
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use