main: logan.pickpocket.main.Pickpocket
name: PickPocket
version: 1.0.8
author: TTG_TRE
soft_depend: [WorldGuard]
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use